name: test_num
description: "Numerology."
publish_to: 'none' 

version: 0.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  ## графика
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  ## система
  auto_route: ^10.0.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7
  freezed: ^3.0.6
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ## генераторы
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.0.1
  json_serializable: ^6.9.5
  freezed_annotation: ^3.0.0
  
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true